# This workflow runs on certain conditions to check for and potentially
# delete container images from the GHCR which no longer have an associated
# code branch.
# Requires a PAT with the correct scope set in the secrets.
#
# This workflow will not trigger runs on forked repos.

name: Container Cleanup

on:
  pull_request:
    types:
      - "closed"
  push:
    paths:
      - ".github/workflows/container-cleanup.yaml"
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:

concurrency:
  group: registry-tags-cleanup
  cancel-in-progress: false

jobs:
  cleanup-untagged-images:
    name: Cleanup Untagged Images Tags for ${{ matrix.primary-name }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - primary-name: "cloudflared"
          - primary-name: "excalidraw"
          - primary-name: "filebrowser"
          - primary-name: "goldpinger"
          - primary-name: "onepassword-connect-api"
          - primary-name: "onepassword-sync"
          - primary-name: "syncthing"
          - primary-name: "x509-certificate-exporter"
    env:
      # Requires a personal access token with the OAuth scope delete:packages
      TOKEN: ${{ secrets.PACKAGE_DELETE_TOKEN }}
    steps:
      - name: Clean untagged images
        if: "${{ env.TOKEN != '' }}"
        uses: stumpylog/image-cleaner-action/untagged@v0.10.0
        with:
          token: "${{ env.TOKEN }}"
          owner: ${{ github.repository_owner }}
          do_delete: "true"
          is_org: "false"
          package_name: "${{ matrix.primary-name }}"
